apiVersion: v1
kind: Service
metadata:
  name: reactivesw-config
  labels:
    name: reactivesw-config
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    name: reactivesw-config
