apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    name: config-service
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30061
  selector:
    app: config-service
