server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/umasuo/config-files
          username: liuquan89@gmail.com
          password: liu37211322quan
