server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/reactivesw/config-files
          username: b
          password: a
          force-pull: true
