server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/reactivesw/config-files
          username: a
          password: b
          force-pull: true

